### ISSUE TITLE
Move to HTML5 Placeholder

### ISSUE THREAD

**Issue by kraftbj** [kraftbj/genesis-enews-extended#106]
Better than inline JS. Would break validation on older G child themes.

**Comment by GaryJones** [comment]
If I did a PR for this, would it be more likely to get in a release quicker?

**Comment by kraftbj** [comment]
That would be very helpful. I'm on paternity until the 1st and not able to
dedicate real time until after getting back to 100%.

A PR (namely from you), I'm happy to push out virtually as it comes in.

**Comment by kraftbj** [comment]
This is next up on the list. The downside to `placeholder` is the IE wonkiness/lack of support. http://caniuse.com/#feat=input-placeholder

That said, I'm fine ripping off the band-aid. Short of keeping JS, any method would break on IE 8/9 depending on site.

**Comment by kraftbj** [comment]
Merged in via 7ce00c47b9944e42bd29600b12bcf845d47dbd6a
