### ISSUE TITLE
Enable usage as shortcode

### ISSUE THREAD

**Issue by kraftbj** [kraftbj/genesis-enews-extended#11]

**Comment by planetahuevo** [comment]
Is this still an approved feature? 
Thanks!

**Comment by kraftbj** [comment]
@planetahuevo It is still on the eventually-list. There are a lot of widget settings in the plugin currently to try to make sense of in a shortcode, so asking people to jump through that much shortcode work (and the support burden of people having trouble with it) have made me pause on it.

No current timeline and it very well may be `wontfix`'d.

**Comment by planetahuevo** [comment]
It is ok. Thank you very much for the update and for the great plugin! :)

**Comment by kraftbj** [comment]
Closing to defer to #136 for an eventual block.
