### ISSUE TITLE
Genesis eNews Extended Optin form

### ISSUE THREAD

**Issue by HikerMom** [kraftbj/genesis-enews-extended#118]
Hi was looking for Brandon Kraft ...

Love this plug. Adds great elegance to a site

But the optin is sending me to a 2nd optin instead of 
my MailChimp "thank you" page.

The 2nd optin has an error message ... yet if you add your
email address, you will then be taken to the Mailchimp "thank you" page.

Is there a way for me to fix this?

This is my form action code: 
 //renegadefinancialplanner.us8.list-manage.com/subscribe/post?u=3f71e8a2580b8bfa84e7f1bec&id=5995a4b36f

I've used it also with 
http://renegadefinancialplanner.us8.list-manage.com/subscribe/post?u=3f71e8a2580b8bfa84e7f1bec&id=5995a4b36f

Thanks... Renee

**Comment by kraftbj** [comment]
Resolved off GitHub
