### ISSUE TITLE
Ajax error on save when MailPoet isn't active

### ISSUE THREAD

**Issue by norcross** [kraftbj/genesis-enews-extended#119]
When adding the widget into a sidebar area, or saving the settings, an undefined index error throws for the MailPoet fields, since they don't exist. below is what I added on my version as a fix, but not sure if this matches up with your desired formatting. this is in the `update` function on line 164

```php
	if ( isset( $new_instance['mailpoet_check'] ) ) {
		$new_instance['mailpoet_check']  = wp_kses_post( $new_instance['mailpoet_check'] );
	}

	if ( isset( $new_instance['mailpoet_subbed'] ) ) {
		$new_instance['mailpoet_subbed']  = wp_kses_post( $new_instance['mailpoet_subbed'] );
	}
```

**Comment by kraftbj** [comment]
I'm down with the braces. The shortcut methods always slow me down when reading through code.
