### ISSUE TITLE
Mailpoet 404 Upon Submission

### ISSUE THREAD

**Issue by tommytomatoe** [kraftbj/genesis-enews-extended#126]
Hey @kraftbj, 

One of my clients has a blog that utilizes this plugin in conjunction with Mailpoet. Upon submission of the form, it takes you to a bad URL with 404 error.

Please try:

http://www.athomewiththeellingtons.com/

After submission:

http://www.athomewiththeellingtons.com/At%20Home%20With%20The%20Ellingtons

The form in question is the one on the sidebar ("STAY UP TO DATE!").

Thank!

**Comment by kraftbj** [comment]
It looks like "At Home With The Ellingtons" has been entered in their Form Action Field widget setting. Can you remove any text from that field?
