### ISSUE TITLE
Not receiving confirmation email

### ISSUE THREAD

**Issue by Christiebry** [kraftbj/genesis-enews-extended#132]
Hello,

I am not receiving email confirmation from Mailchimp for a certain email list. I tired another account, put in the form action and it worked fine. But for the list I need it set up for I do not receive a confirmation. I get the "Almost Finished...." screen but then no email comes through to confirm.

Any idea why this would be?

Thank you
C

**Comment by kraftbj** [comment]
No idea. I would suggest contacting MailChimp support. eNews Extended only passes information on to MailChimp and if they accepted the form (as suggested by "Almost finished") something else is afoot. If they can provide any information that would suggest eNews is involved, please drop a note here.
