### ISSUE TITLE
Aweber not integrating with Genisis Enews Extended

### ISSUE THREAD

**Issue by daetoro** [kraftbj/genesis-enews-extended#134]
Hi,
 I am having difficulty with integrating aweber form to genesis enews, when inputing name and email I am receiving a error message stating that required fields are missing! even though the field was submitted

How do I fix the coding issue when implementing the code from my aweber form into the genesis widget?

**Comment by kraftbj** [comment]
My guess is that the settings weren't entered right -- the field name doesn't match what Aweber is expecting. The best info I have on Aweber specifically is from https://kraft.blog/question/aweber/

**Comment by Fr0udy** [comment]
Better late than never but see issue #155
