### ISSUE TITLE
Hidden field clash with Button text

### ISSUE THREAD

**Issue by janiani** [kraftbj/genesis-enews-extended#143]
Hi Brandon

Have created an optin using the hidden field for gdpr, great.  But the button text is sitting flush next to it instead of being on a different line.  Ideally would like the hidden field below the button.  I've played around with Inspect Element but can't quite see what's causing it.

Can you advise?

Many thanks.

![gen enews extended button and hidden field issue](https://user-images.githubusercontent.com/13997512/44399409-66bd3a00-a53f-11e8-8bff-158ed9f36626.png)

**Comment by kraftbj** [comment]
Can you provide your site's URL? Most likely, you'll want to add some CSS to adjust for it.

**Comment by janiani** [comment]
Thanks.  

http://www.janeunsworth.com/7-ways-to-break-up-with-chronic-stress/

Someone in the Gen WP FB Group gave me this code:

.enews-widget input[type="submit"] {
display: block;
max-width: 100%;
margin: 0 auto;
}

But I want the button to be above the hidden field if you could help with that?

**Comment by kraftbj** [comment]
Hi @janiani  - rearranging the order might be possible with some css or javascript, but not something supported by the plugin directly.
