### ISSUE TITLE
Duplicate subbox and subbutton IDs when multiple eNews widgets used

### ISSUE THREAD

**Issue by nickcernis** [kraftbj/genesis-enews-extended#144]
Duplicate form IDs were solved in #113.

But using multiple eNews widgets on a single page still results in duplicate IDs for subbutton and subbox:

```HTML
<form id="subscribeenews-ext-2" action="#" method="post" …>
<label for="subbox" class="screenread">Your Email Address</label><input type="email" value="" id="subbox" placeholder="Your Email Address" name="#" required="required">
<input type="submit" value="Sign Up" id="subbutton">
</form>
```

**Comment by kraftbj** [comment]
That's a bit of a BC nightmare there.

In trying to preserve styling for some older themes that style on `#subbutton`, etc, we can't use different ones without breaking styling.

My goal is to create a eNews block that will deprecate the widget and won't suffer from that defect.
