### ISSUE TITLE
Where are form submissions saved within the site?

### ISSUE THREAD

**Issue by emily-magnificent** [kraftbj/genesis-enews-extended#145]
I was having my Genesis eNewsletter form submissions sent to my admin email (not a list newsletter builder), which was working originally but I noticed about a month ago I was not getting them. 

**Is there somewhere within the plugin where attempted form submissions are stored? I feel like I lost some important leads during that time and would like to retrieve them.** 

Any help is greatly appreciated. Thanks!

**Comment by kraftbj** [comment]
Hi @emily-magnificent, the widget does not process the form submission at all. Whatever the form action field is set to—that location processes the submission—nothing is handled by this plugin itself. It's a "dumb" widget, just helping to present a form that fits the style structure of StudioPress at the time.
