### ISSUE TITLE
'Multiple form label' alerts 

### ISSUE THREAD

**Issue by shanemery** [kraftbj/genesis-enews-extended#148]
I'm showing 'multiple form label' alerts for the Genesis eNews Extended widget when I run a test using the WAVE tool. For some reason the alerts don't appear on the widget when I'm on my homepage, but the alerts are showing for the widget on all of my individual posts. Is there a fix for this? Thank you!
Homepage: https://wave.webaim.org/report#/https://www.passmesometasty.com/
Post: https://wave.webaim.org/report#/https://www.passmesometasty.com/roasted-red-pepper-tomato-basil-soup/

**Comment by kraftbj** [comment]
Ah, I see what's happening. You're using two instances of the widget on individual post pages, so there is a duplication.

I believe I can refactor how the `label` element is used to make it implicit which element it is being used for and thus able to drop the `for` that is causing the issue.
